### ISSUE TITLE
local.json's language code problem.

### ISSUE THREAD

**Issue by 2jun0** [Heroor/md-reader#16]
The language code "en-US", "zh-CN" have problem.
English code and Chinese code is not only one.

This extension can't detect `en-GB`, `en-CA`, `en-IN`, `zh-SG(singapore)`,  etc

In particular, I think English should be grouped into `en`.

**Comment by 2jun0** [comment]
_My English is bad so please if you don't understand, tell me_

**Comment by Heroor** [comment]
This is the case, only `en-US` and `zh-CN` are defined in the code, and other undefined languages will use `en-US` by default.

**Comment by 2jun0** [comment]
I wanted to talk about structural issues about adding new languages (Polish, French and Spanish, they have many language codes). but this version doesn't have a lot of language codes, so I'll close the issue.

**Comment by Heroor** [comment]
It's ok, we can add in in the future.

**Comment by Heroor** [comment]
I adjusted the language matching strategy, and now we can add i18n for any language, just by modifying 'local.json'.
