### ISSUE TITLE
Why don't you remove popup's max-height?

### ISSUE THREAD

**Issue by 2jun0** [Heroor/md-reader#17]
https://github.com/Heroor/md-reader/blob/764de06f9d08440ea5f66797a31436b4dc69224d/src/popup/components/app.svelte#L143

> In 中文, 
> It looks good to me.

![image](https://user-images.githubusercontent.com/7973448/139779217-0f14e2fb-308c-45fb-b465-182a913623f6.png)

> But in the other languages sidebar still appear.

![image](https://user-images.githubusercontent.com/7973448/139779153-54cddcf1-ae1c-411a-ba9f-3582d983bda7.png)

> So, why don't you remove popup's max-height?

**Comment by Heroor** [comment]
Oh, I didn't find this problem, It works fine on my computer:
<img width="340" alt="截屏2021-11-02 上午11 38 45" src="https://user-images.githubusercontent.com/19926530/139783538-8fa89deb-c0b3-4eb8-aaef-f8d53e07d221.png">

In the past, the content of the pop-up window was very small, only when the warning message was displayed, it would be too long. I hope it can be simple, so I add the max-height. Now it has too much content and can be removed

But the pop-up window still has a default maximum height:

<img width="345" alt="截屏2021-11-02 上午11 36 57" src="https://user-images.githubusercontent.com/19926530/139787644-4bd8ec04-1914-4ee7-9522-3264d603e5b9.png">

**Comment by 2jun0** [comment]
I got it, I think this issue is due to the display environment.
Or It might be because our operating system is different.

How about using `rem` unit?

when I had max-height set `33rem`, It show better

![image](https://user-images.githubusercontent.com/7973448/139800946-a6b91b30-c337-4726-bb3f-fde8efdd4434.png)

![image](https://user-images.githubusercontent.com/7973448/139801070-c2443356-7229-43aa-8021-6c64937bf062.png)

**Comment by Heroor** [comment]
The default maximum height of the window is 600px, but if I set 600px, two scroll bars will appear. I set 599px to work, so that can keep the border design and fit as much content as possible.

**Comment by 2jun0** [comment]
Okay! Thank you for help!
